### ISSUE TITLE
HealthRiskCreated

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#153] opened 2017-10-01 08:02 UTC
Information needed: 

- ID
- Name of health risk
- Key message

Edit: Our current event:

        public Guid Id { get; set; }
        public string Name { get; set; }
        public int ReadableId { get; set; }
        public string CaseDefinition { get; set; }

        public string Note { get; set; } //TODO: To be split into a separate command
        public string CommunityCase { get; set; }  //TODO: To be split into a separate command
        public string KeyMessage { get; set; }

**Comment by roarfred** [comment] 2017-10-01 22:49
Completed as of PR #194
Please note that "Id" is really the key of the data store, so the field used as ID by end users is implemented as ReadableId

The complete attributes of the event are now:
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int ReadableId { get; set; }
        public int? Threshold { get; set; }
        public string ConfirmedCase { get; set; }
        public string Note { get; set; }
        public string SuspectedCase { get; set; }
        public string ProbableCase { get; set; }
        public string CommunityCase { get; set; }
        public string KeyMessage { get; set; }

Test data in the admin project feeds from the spreadsheet at https://docs.google.com/spreadsheets/d/1bfbfaTr6jx3ia7tOEZxDMDk-qrWAfS9vCoH2N-TG9zM/edit#gid=0 There are however no values for KeyMessage here. Would be nice to get some samples, if available...

**Comment by karolikl** [comment] 2017-10-02 06:56
Great! What happens when a health risk is updated, will it emit the HealthRiskCreated event (if so, maybe we should rename it) or will it emit a separate event?

**Comment by roarfred** [comment] 2017-10-02 07:13
There should at least be a similar HealthRiskUpdated event, but ref my comment in #139, this is not crystal clear at the moment

**Comment by Velcrow81** [comment] 2017-10-19 20:22
What is Threshold and why is it nullable? Acording to @einari, there should never be nullables in events since that brings uncertainty, confusion, leg pains and an early death :)

**Comment by roarfred** [comment] 2017-10-19 20:57
Threshold is a value used as a default threshold for when an alert should be sent. (The number of incidents reported, but there should also be a timespan here to make any sense)

Remember, for some of us in the Rec Cross society, nullable values, uncertainty, cunfusion, leg pains and early deaths are just another day in life :) I will try to make myself believe there is a world without such pain, and write my code accordingly...

**Comment by einari** [comment] 2017-10-20 13:30
👍  Anything on an event has happened, it is not optional. If you need optional, model that as a separate event. Question is if the event could be broken up into separate pieces. 

I could potentially see the following:

HealthRiskCreated / Registered
HealthRiskThresholdDefined
HealthRiskNoteAdded

and more.. 

It depends on wether or not everything is needed for a health risk to exist, but since some of these things might be editable on their own - you could keep them as separate events and in the controller generate multiple events.

**Comment by eprom** [comment] 2018-08-20 19:06
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.

**Closed by eprom** 2018-08-20 19:06 UTC
Labels: Admin, event
