### ISSUE TITLE
Case Reports on dev.cbsrc.org/reporting are duplicated

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#669] opened 2018-04-22 09:42 UTC
Something is triggering the duplication of case reports listed in the case reports list in reporting/case-report/list .

A few days ago I saw the duplication of case reports before April 18. , then @aninek sent a case report which showed up and was not duplicated.

And today, it seems that all case reports again have been duplicated.

@einari, @karolikl, @jakhog

**Comment by jakhog** [comment] 2018-04-22 09:56
They are duplicated in MongoDB:
```
> db.CaseReportForListing.find({}, { DataCollectorDisplayName: true, Message: true, Timestamp: true }).sort({ Timestamp: -1 })
{ "_id" : BinData(3,"mYNy7fq+mkaAPLAt4Ea9Vg=="), "DataCollectorDisplayName" : "Unknown", "Message" : "Message From SMSSync", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"i/r7Jv3UmkWrA31F/8m4tw=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#0#1", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"tpDgE6TaCEqddwXVqruoBQ=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#1#1", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"dlbMtT1IXEyg3YHIUlX/qg=="), "DataCollectorDisplayName" : "Unknown", "Message" : "Message From SMSSync", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"M9SKDQLFCU2dvV6jcjMalQ=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#0#1", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"L1IQlZJUFEq/gjGwp0FZxQ=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#1#1", "Timestamp" : [ NumberLong("636598300800000000"), 120 ] }
{ "_id" : BinData(3,"hZ090IBQ3kSFkVf/UhfREg=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#1#56", "Timestamp" : [ NumberLong("636597270080000000"), 120 ] }
{ "_id" : BinData(3,"nMdbsZiJm0+hCO2iNh4D1w=="), "DataCollectorDisplayName" : "Unknown", "Message" : "7#1#56", "Timestamp" : [ NumberLong("636597270080000000"), 120 ] }
{ "_id" : BinData(3,"Qs3ROiv21kmlkjh2ycfpAQ=="), "DataCollectorDisplayName" : "Bjørn", "Message" : null, "Timestamp" : [ NumberLong("636596743130000000"), 120 ] }
{ "_id" : BinData(3,"8siodKj/kkKNmcqsoOgyUA=="), "DataCollectorDisplayName" : "Bjørn", "Message" : "1#1#1", "Timestamp" : [ NumberLong("636596743130000000"), 120 ] }
{ "_id" : BinData(3,"41BJxTZOvkqElW204qIgqA=="), "DataCollectorDisplayName" : "aninek", "Message" : "Why are you reporting everything double, cbs?", "Timestamp" : [ NumberLong("636596462930000000"), 120 ] }
{ "_id" : BinData(3,"MjObr5DIZ0KUBQZNhBkHSQ=="), "DataCollectorDisplayName" : "aninek", "Message" : "Why are you reporting everything double, cbs?", "Timestamp" : [ NumberLong("636596462930000000"), 120 ] }
{ "_id" : BinData(3,"1tQJHBvIPUW7eIrwdvRe3g=="), "DataCollectorDisplayName" : "petter", "Message" : "Du har mottatt en MMS fra +4793036969. Gå til http://telia.no/mmsfremviser innen 10 dager. Bruk ditt nummer og passord:  Ewv4QL2S . Hilsen Telia.\n", "Timestamp" : [ NumberLong("636592928930000000"), 120 ] }
{ "_id" : BinData(3,"0whxZ0E1L0mTDTeNTm14jA=="), "DataCollectorDisplayName" : "petter", "Message" : "Du har mottatt en MMS fra +4793036969. Gå til http://telia.no/mmsfremviser innen 10 dager. Bruk ditt nummer og passord:  Ewv4QL2S . Hilsen Telia.\n", "Timestamp" : [ NumberLong("636592928930000000"), 120 ] }
{ "_id" : BinData(3,"p9TlIYjmHEeXoFmTFK4G7A=="), "DataCollectorDisplayName" : "petter", "Message" : "Du har mottatt en MMS fra +4793036969. Gå til http://telia.no/mmsfremviser innen 10 dager. Bruk ditt nummer og passord:  Ewv4QL2S . Hilsen Telia.\n", "Timestamp" : [ NumberLong("636592928930000000"), 120 ] }
{ "_id" : BinData(3,"VeAwyAIMLkK5kccA0LMqiQ=="), "DataCollectorDisplayName" : "Sindre", "Message" : "You performed well today CBS, maybe too well? #£&_-+=) (@':%/*\",.!? ☺😊😂😀😄😈😅😈😡😢😴", "Timestamp" : [ NumberLong("636592387130000000"), 120 ] }
{ "_id" : BinData(3,"scYa6A2mt0ibRBBXXPk4Fg=="), "DataCollectorDisplayName" : "Sindre", "Message" : "You performed well today CBS, maybe too well? #£&_-+=) (@':%/*\",.!? ☺😊😂😀😄😈😅😈😡😢😴", "Timestamp" : [ NumberLong("636592387130000000"), 120 ] }
{ "_id" : BinData(3,"fwh79qlDL02z5af99NhG4g=="), "DataCollectorDisplayName" : "Sindre", "Message" : "You performed well today CBS, maybe too well? #£&_-+=) (@':%/*\",.!? ☺😊😂😀😄😈😅😈😡😢😴", "Timestamp" : [ NumberLong("636592387130000000"), 120 ] }
{ "_id" : BinData(3,"WcZ1mtPqB0GCTwol0nCuRg=="), "DataCollectorDisplayName" : "Vidar", "Message" : null, "Timestamp" : [ NumberLong("636592080090000000"), 120 ] }
{ "_id" : BinData(3,"2t+D05WioEa2lvzi9cB/kg=="), "DataCollectorDisplayName" : "Vidar", "Message" : null, "Timestamp" : [ NumberLong("636592080090000000"), 120 ] }
Type "it" for more
```

So somewhere, they are written multiple times to the database...

**Comment by woksin** [comment] 2018-04-22 12:54
But it's weird since it's seemingly not duplicated when the sms is first sent. You can send a report and it shows up as a single case report, so in my mind there must be a external event that triggers the duplication in the dev environment

**Comment by einari** [comment] 2018-04-22 13:02
One of the changes that was done prior to the field test was to allow unique Kafka Event Processors per machine it was running on when running in Development - Non-production. Basically appending the host name of the machine to the name of the consumer, to allow it to act as a unique but predictable consumer. 

It was my working theory that the reason we're seeing duplicates was because of this fact - developer would fire up VolunteeerReporting locally and being behind in the event stream in Kafka, you'd get them all again and then if using the production database - you'd get duplicates.

But this might be a completely wrong theory as I'm seeing in Kafka that there are 3 consumers registered for text messaging, 1 production  and 2 being myself and I haven't ran the VolunteerReporting since the field test day..

**Comment by eprom** [comment] 2018-09-03 15:29
This issue is not happening on the production. If Kafka were the cause, DoLittle is planning to replace Kafka with gRPC. I am closing it for now, we can reopen it if there is a need.

**Closed by eprom** 2018-09-03 15:29 UTC
Labels: Volunteer Reporting, bug, high-priority
