### ISSUE TITLE
Don't display case 99 reports in the Case reports list

### ISSUE THREAD

**Issue by cathinkaw** [IFRCGo/cbs#1020] opened 2019-04-12 09:06 UTC
As a data verifier I don't want to see activity 99 case reports in the list of case reports.
There reports are just a way of showing that they are still active.

The filtering should be done in backend

(Case reports 99 should instead update the last active status which is a seperate task https://github.com/IFRCGo/cbs/issues/1019)

**Comment by jakhog** [comment] 2019-04-13 09:52
Duplicate of #930

**Closed by jakhog** 2019-04-13 09:52 UTC
Labels: Reporting, backend, good first issue
