### ISSUE TITLE
Register data collection point

### ISSUE THREAD

**Issue by gardnk** [IFRCGo/cbs#1039] opened 2019-04-13 11:34 UTC
In addition to registering data collectors as individuals there needs to be an option to register data collectors as a point, where no individual information like name and gender is needed. 

This is needed when all phone numbers used for reporting are linked to a point instead of a person.

**Comment by esp0** [comment] 2019-07-03 17:29
Closed as duplicate of #1105

**Closed by esp0** 2019-07-03 17:29 UTC
Labels: Reporting
