### ISSUE TITLE
Send confirmation SMS to Data Collector after registration

### ISSUE THREAD

**Issue by dageirikboe** [IFRCGo/cbs#585] opened 2018-04-03 10:10 UTC
After a Data Collector is registered with all relevant information, the system should send a confirmation SMS to the Data Collector with confirmation of registration and the contact details of their Data Verifier.
Ref. User story P03.03

**Comment by karolikl** [comment] 2019-04-03 18:30
Duplicate of #375

**Closed by karolikl** 2019-04-03 18:30 UTC
Labels: User Management
